version: "3.2"

#Before launching docker-machine
# export VIRTUALBOX_SHARE_FOLDER="$PWD:$PWD"

services:
  api:
    image: golang:1.11
    volumes:
      - ./:/go/src/bmstu.codes/developers34/SBWeb
    working_dir: /go/src/bmstu.codes/developers34/SBWeb
    command: go run bmstu.codes/developers34/SBWeb -cfg ./internal/configForDocker.json
    links:
      - redis
      - postgres
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host

  redis:
    image: redis:alpine

  postgres:
    volumes:
      - ./internal/db/data/init.sql:/docker-entrypoint-initdb.d/init.sql
      # - /var/lib/postgresql/data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_DB: data
      POSTGRES_INITDB_ARGS: "-l en_US.UTF-8 -E UTF8"
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: dataUSER
      POSTGRES_PASSWORD: dataPASSWORD
    #restart: always
    image: postgres:alpine