version: "3.2"

#Before launching docker-machine
# export VIRTUALBOX_SHARE_FOLDER="$PWD:$PWD"

services:
  api:
    image: golang:1.11
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./:/go/src/bmstu.codes/developers34/SBWeb
    working_dir: /go/src/bmstu.codes/developers34/SBWeb
    command: go run bmstu.codes/developers34/SBWeb -cfg ./pkg/configForDocker.json
    links:
      - redis
      - postgres
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
  

  redis:
    image: redis:alpine

  postgres:
    volumes:
      - ./pkg/db/data/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: data
      POSTGRES_INITDB_ARGS: "-l en_US.UTF-8 -E UTF8"
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    image: postgres:alpine